detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  UtilityFunction:
    public_methods_only: true

directories:
  "app/controllers":
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false

exclude_paths:
  - db/migrate
  - vendor
  - bin/
