# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# rubocop:disable Lint/Void: Literal
# rubocop:disable Metrics/LineLength
[User.create(name: 'Utest1', email: 'user@test.ru', password: '123456', password_confirmation: '123456', info: '', skills: [], role: nil),
 User.create(name: 'Utest2', email: 'user@test2.ru', password: '123456', password_confirmation: '123456', info: '', skills: [], role: nil),
 User.create(name: 'Utest3', email: 'user@test3.ru', password: '123456', password_confirmation: '123456', info: '', skills: [], role: nil)]

[Project.create(title: 'Project 1-1', user_id: User.first.id, info: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et viverra nisi. Morbi pulvinar, risus id porttitor dictum, erat purus pretium quam, vitae ultricies arcu enim ac ex. Etiam ac ligula at nibh pharetra ornare. Nulla congue non dui ac molestie. Integer at semper enim, non consectetur elit. Morbi consectetur vitae nulla ut venenatis. Sed vestibulum sit amet urna vel sollicitudin. In eu bibendum enim. Phasellus hendrerit venenatis ante sit amet euismod. Ut in condimentum metus, ut pretium ante. Donec ornare porttitor risus eu mollis. Aenean semper semper volutpat.', skills: [], project_type: 'project_type', cost: 0, cost_type: 'price', deadline: "Sat, 31 Aug 2019"),
 Project.create(title: 'Project 1-2', user_id: User.first.id, info: 'Hello, I have a requirement of overhauling my current resume - Revamp it to make it professional as per Canadian requirements. - Tailor it to the job description - Make it ATS Compatible. I would prefer someone who had past experience of resume writing for Project Managers. Any experience or understanding of the Rail/Transit industry/business will be an additional advantage. This requirement will continue until I get a job in Canada.', skills: [], project_type: 'project_type', cost: 0, cost_type: 'price', deadline: "Sat, 31 Aug 2019"),
 Project.create(title: 'Project 1-3', user_id: User.first.id, info: 'We want to deploy a rails app with RDS (Aurora PostgreSQL) and using Capistrano. ', skills: [], project_type: 'project_type', cost: 0, cost_type: 'price', deadline: "Sat, 31 Aug 2019"),
 Project.create(title: 'Project 2-1', user_id: User.second.id, info: "Needs to hire somebody who is fluent/native in English to make 300+ cold calls per day using Mojo to prospect distressed home sellers through data lists (probate, tax delinquent, pre-foreclosure, etc.) The ability to qualify potential sellers over the phone, run quick comps for that specific area, and set up appointments for myself and my team to close the deals. Having the ability to suggest ideas based on experience in the Real Estate Investing world is a huge asset, as well as prior experience filling this sort of position. Daily tasks would include: 1) 300+ outbound calls 2) Pre-screening leads 3) Setting appointments 4) Running rough comps on location/area 5) Utilizing Call Rail to answer voicemails 6) Data scraping There may be other minor jobs during the day, but major priority is getting in contact with motivated sellers who we can qualify and close. Ideally, you'll understand the importance of follow up and be sure to stay organized with possible sellers throughout the process", skills: [], project_type: 'project_type', cost: 0, cost_type: 'price', deadline: "Sat, 31 Aug 2019"),
 Project.create(title: 'Project 2-2', user_id: User.second.id, info: 'Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before. Many say exploration is part of our destiny, but it’s actually our duty to future generations and their quest to ensure the survival of the human species.', skills: [], project_type: 'project_type', cost: 0, cost_type: 'price', deadline: "Sat, 31 Aug 2019"),
 Project.create(title: 'Project 2-3', user_id: User.second.id, info: 'Bacon ipsum dolor amet short ribs brisket venison rump drumstick pig sausage prosciutto chicken spare ribs salami picanha doner. Kevin capicola sausage, buffalo bresaola venison turkey shoulder picanha ham pork tri-tip meatball meatloaf ribeye. Doner spare ribs andouille bacon sausage. Ground round jerky brisket pastrami shank.', skills: [], project_type: 'project_type', cost: 0, cost_type: 'price', deadline: "Sat, 31 Aug 2019"),
 Project.create(title: 'Project 3-1', user_id: User.third.id, info: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et viverra nisi. Morbi pulvinar, risus id porttitor dictum, erat purus pretium quam, vitae ultricies arcu enim ac ex. Etiam ac ligula at nibh pharetra ornare. Nulla congue non dui ac molestie. Integer at semper enim, non consectetur elit. Morbi consectetur vitae nulla ut venenatis. Sed vestibulum sit amet urna vel sollicitudin. In eu bibendum enim. Phasellus hendrerit venenatis ante sit amet euismod. Ut in condimentum metus, ut pretium ante. Donec ornare porttitor risus eu mollis. Aenean semper semper volutpat.', skills: [], project_type: 'project_type', cost: 0, cost_type: 'price', deadline: "Sat, 31 Aug 2019"),
 Project.create(title: 'Project 3-2', user_id: User.third.id, info: 'Cupcake ipsum dolor. Sit amet marshmallow topping cheesecake muffin. Halvah croissant candy canes bonbon candy. Apple pie jelly beans topping carrot cake danish tart cake cheesecake. Muffin danish chocolate soufflé pastry icing bonbon oat cake. Powder cake jujubes oat cake. Lemon drops tootsie roll marshmallow halvah carrot cake.', skills: [], project_type: 'project_type', cost: 0, cost_type: 'price', deadline: "Sat, 31 Aug 2019"),
 Project.create(title: 'Project 3-3', user_id: User.third.id, info: 'Those options are already baked in with this model shoot me an email clear blue water but we need distributors to evangelize the new line to local markets, but fire up your browser. Strategic high-level 30,000 ft view. Drill down re-inventing the wheel at the end of the day but curate imagineer, or to be inspired is to become creative.', skills: [], project_type: 'project_type', cost: 0, cost_type: 'price', deadline: "Sat, 31 Aug 2019")]
# rubocop:enable Lint/Void: Literal
# rubocop:enable Metrics/LineLength
