# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

[User.create(name: 'Иван Натанович', email: "ivan_natanovich@mail.ru", password: '123456', password_confirmation: '123456', confirmed_at: Time.now.utc, info: 'Небольшая компания, но у нас есть печеньки.', skills: [], role: "customer", phone_number: "+375291111111", company_name: "ИП Натан"),
User.create(name: 'Натан Иванович', email: "natan_ivanovich@mail.ru", password: '123456', password_confirmation: '123456', confirmed_at: Time.now.utc, info: 'Одна из крупнейших компаний', skills: [], role: "customer", phone_number: "+375292222222", company_name: 'ЧУП Иван'),
User.create(name: 'Натан Натанович', email: "natan_natanovich@mail.ru", password: '123456', password_confirmation: '123456', confirmed_at: Time.now.utc, info: 'IT-компания', skills: [], role: "customer", phone_number: "+375293333333", company_name: 'ООО Супер-Прог')]

[Project.create(title: 'Доработать приложение на Swift', user_id: User.first.id, info: 'Добрый вечер исполнители. Есть готовый проект на Swift калькулятор. Нужна помощь в доработке функционала 3-х кнопок. \r\n\r\nЕсть общий лейбел ввода данных где отображаются цифры есть дублирующий где отображаются вся информация 45+5-6=44 - это как пример.\r\n\r\n1 - удалить посимвольно. Заблокировать ввод пока не удалено до знака равно(45+5-6=44). Все остальные данные пересчитывать при нажатии знака равно.\r\n\r\n2 - удалить последнее действие 45+5-6=44, при первой нажатии удаляем =44, при втором -6 и т.д\r\n\r\n3- вернусь последнее действие вернуть - 6 при втором нажатии возвращаем = 44', skills: ['Swift', 'iOS'], project_type: 'project_type', cost: 25, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: 'Разработка Приложения под IOS', user_id: User.second.id, info: 'Всем привет! Ищем Middle IOS Developer,  для добавления новых фич + рефакторинг в уже существующем приложении написанном на Swift. В общей сложности работ месяца на 4. Разработчик должен будет работать фул-тайм.', skills: ['Swift', 'iOS'], project_type: 'project_type', cost: 2000, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: 'Разработчик на SWIFT', user_id: User.third.id, info: 'На постоянную удаленную работу требуется разработчик Mac OS (Objective-C / Swift)\r\n\r\n\r\nВ ключевые обязанности будет входить:\r\n\r\n- Разработка native GUI приложения под Mac OS X согласно подробному ТЗ и дизайну (тематика: оптимизация OS)\r\n\r\n- Проведение технических исследований и экспертиз\r\n\r\n- Работа с системой контроля версий и баг трекерами\r\n\r\n\r\nМы ищем специалиста, который:\r\n\r\n- Обладает 3-х летним опытом коммерческой разработки под MacOS X или iOS (Objective-C; Swift отдаем преимущество)\r\n\r\n- Понимает принципы работы GUI приложений\r\n- Знает принципы проектирования ПО и оптимизации производительности\r\n\r\n- Обладает опытом разработки многопоточных приложений\r\n- Знает английский язык на уровне technical read/write\r\n\r\n\r\nУсловия, которые мы предлагаем:\r\n\r\n\r\n- Возможность работать удаленно из любой точки мира\r\n- Достойная зарплата (в USD) плюс бонусы по результатам работы\r\n- Оплачиваемый отпуск\r\n- Полная занятость, гибкий график\r\n- Работа в дружном коллективе\r\n- Перспективы профессионального роста\r\n\r\n\r\n*Мы будем признательны, если Вы укажете размер желаемой заработной платы в своем резюме или сопроводительном письме, однако окончательный уровень финансового вознаграждения будет обсуждаться с каждым соискателем индивидуально.\r\n\r\n\r\nНа предложение, со стороны компании, напрямую влияют: соответствие вышеперечисленным требованиям, объем и тематика портфолио (мы готовы рассмотреть работы выполненные также и для iOS), Ваши знания, продемонстрированные на техническом интервью. \r\n\r\n\r\n\r\nОтправляя резюме ОБЯЗАТЕЛЬНО в сопроводительном письме укажите свое ФИО, контактный e–mail и ССЫЛКУ НА ПОРТФОЛИО (или список проектов).', skills: ['Swift', 'iOS'], project_type: 'project_type', cost: 2500, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: 'Junior Ruby on Rails developer', user_id: User.first.id, info: 'В команду нужен начинающий RoR программист для помощи по проекту. \r\n\r\nРабота удаленная, связь через чат в мессенджерах или скайп голосом  Работа хорошо подойдет начинающим.\r\n\r\n\r\nТребования\r\n\r\n    Опыт в web, SaaS, Rails\r\n    Опыт с Linux серверами\r\n    Docker (не обязательно)\r\n    Хороший уровень front-end\r\n    Опыт удаленной работы\r\n\r\n\r\nСпасибо.', skills: ['RoR', 'Linux'], project_type: 'project_type', cost: 600, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: 'Настроить добавление в БД (Ruby on Rails)', user_id: User.second.id, info: 'Есть restclient ruby и встроенная библиотека json - выгружается ответ API, но есть какая-то проблема с его разбором или проблема с этим вот restclient, потому что уходит в таймаут. Возможно ActiveRecord не настроен правильно, так как не добавляет в БД. \r\n\r\n\r\nНужно просто в этом ориентироваться, чтобы решить проблему.\r\n\r\n\r\nЕсли вы шарите в Ruby - пишите!', skills: ['RoR', 'Ruby'], project_type: 'project_type', cost: 1, cost_type: 'contract_price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: 'Web игра', user_id: User.third.id, info: 'Необходимо разработать веб игру по типу игры \"змейка\", где игра будет проходить в реальном времени, где множество игроков играют в роли змейки или червя на одной карте и пытаются нарастить свою массу, длину и размер, чтобы стать самой большой змейкой и попасть в список лидеров.', skills: ['Node.js'], project_type: 'project_type', cost: 300, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: 'Разработка JavaScript игр', user_id: User.first.id, info: 'Нужен разработчик простых JavaScript игр на платформе Spark AR для постоянного сотрудничества.\r\n\r\n\r\nSpark AR: https://sparkar.facebook.com/ar-studio/\r\n\r\n\r\nЖелательно город Киев.', skills: ['React', 'HTML', 'CSS'], project_type: 'project_type', cost: 800, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: 'Требуется C# Asp.Net/MVC .NetCore разработчик на длительный срок.', user_id: User.second.id, info: 'Требуется Asp.Net C# программист для удалённой работы.\r\n\r\nНеобходимые навыки: \r\n\r\n- Знания ООП, шаблонов проектирования.\r\n\r\n- Уверенное знание Asp.Net/MVC/C#, Asp.Net Core\r\n\r\n- Разработка на Backend с применением TDD\r\n\r\n- Возможность работать как над веб так и над C# проектами (разработка библиотек)\r\n\r\n- Опыт разработки БД, MsSql, администрирования \r\n\r\n- jQuery, Angular, Backbone, TypeScript и т.д.\r\n\r\n- ajax, javasrcipt, html, css \r\n\r\n- Системы контроля версий, Git.\r\n\r\n- Опыт вёртски\r\n\r\n- Работа с багтрекером.\r\n\r\n- Ответственность, коммуникабельность, возможность быть онлайн в рабочее время\r\n\r\n- Знание английского на уровне понимания задач, участия в чтении переписки.\r\n\r\nРабота в Agile команде на полный день. Просьба, если Вы рассчитываете на подработку - не откликаться на данную вакансию - вакнсия на ПОЛНЫЙ ДЕНЬ!', skills: ['MsSql' '.NET' 'C#'], project_type: 'project_type', cost: 1700, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: 'Создание Игрового сервера: C#, JS,HTML,CSS,MySQL', user_id: User.third.id, info: 'Требуется Программист для создания игрового сервера на платформе Rage MP для GTA 5 владеющий: C#, JS, MySQL, HTML, CSS. Требуется программист как на отдельном ЯП, так и на всех требующихся.\r\nПрограммист требуется как на постоянную основу так и на аутсорсинг.\r\n\r\nСервер состоит из 20-30 модулей, разной сложности. Приблизительное протяженность работ 2-4 месяца с момента начала разработок.  Заработная плата за каждый модуль. Стоимость услуг обговаривается индивидуально с каждым разработчиком, заранее после ознакомления с ТЗ, оплата сразу после тестирования. За 1 модуль цена от 500 р до 10.000 рублей. На фиксированную ЗП не рассматриваем.  Оплата любым удобным для вас способ, либо через данный сайт либо напрямую.\r\n\r\nТребуется:\r\n1 постоянный программист. (Оплата за каждый модуль + надбавка за внедрения других модулей)\r\n\r\n2 программиста на аутсорс. (Оплата за каждый модуль)\r\n\r\nВся необходимая документация по Rage Multiplayer находится в открытом доступе, а так же поддержка на форуме. \r\n\r\nПри оставление заявки, указывайте:\r\nВаши контакты для связи (Skype, discord, VK, WhatsApp, Telegram)\r\n\r\nВаш опыт в разработках\r\nВаши предпочтения(одному все делать или же нужны помощники)', skills: ['C#', 'JS', 'MySQL', 'HTML', 'CSS'], project_type: 'project_type', cost: 1000, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: 'Требуется PHP (Laravel) разработчик для постоянной работы.', user_id: User.first.id, info: 'Доброе время суток!\r\nТребуется full stack (PHP, Laravel) программист для постоянной работы.\r\n\r\nТребования:\r\n- Уверенное знание PHP (2+ года)\r\n- Опыт использования фреймворка Laravel (1+ год)\r\n- Знание и использование принципов ООП\r\n- Опыт проектирования и работы с MySQL + понимание, как писать оптимизированные запросы к БД\r\n- Знания JavaScript; AJAX\r\n- Опыт написания и работы с REST API\r\n- Понимание основ HTML, CSS, Bootstrap\r\n\r\nЛичные качества:\r\n- Умение ориентироваться и разбираться в чужом коде\r\n- Умение давать адекватную оценку на разработку и выполнять поставленные задачи в оговоренный срок\r\n- Организованность, ответственность, профессионализм, добросовестность\r\n\r\nУсловия:\r\n- Удаленная работа и свободный график\r\n- Оплата: 10$/час, выплата 1 раз в месяц\r\n- Минимум 5 продуктивных часов в день, 5 дней в неделю\r\n- Учёт продуктивных часов при помощи Time Tracking программы (yaware)', skills: ['PHP', 'HTML', 'CSS', 'Bootstrap'], project_type: 'project_type', cost: 1000, cost_type: 'price', deadline: rand(1.month).seconds.from_now)]
