# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

[User.create(name: 'Иван Первич', email: 'user1@demo.com', password: '123456', password_confirmation: '123456', confirmed_at: Time.now.utc, info: 'Небольшая компания, но у нас есть печеньки.', skills: [], role: 'customer', phone_number: '+375291111111', company_name: 'ИП Натан'),
User.create(name: 'Натан Другич', email: 'user2@demo.com', password: '123456', password_confirmation: '123456', confirmed_at: Time.now.utc, info: 'Одна из крупнейших компаний', skills: [], role: 'customer', phone_number: '+375292222222', company_name: 'ЧУП Иван'),
User.create(name: 'Петр Третьич', email: 'user3@demo.com', password: '123456', password_confirmation: '123456', confirmed_at: Time.now.utc, info: 'IT-компания', skills: [], role: 'customer', phone_number: '+375293333333', company_name: 'ООО Супер-Прог'),
User.create(name: 'Юзер Разработич', email: 'user1@test.com', password: '123456', password_confirmation: '123456', confirmed_at: Time.now.utc, info: '', skills: [], role: 'developer', phone_number: '', company_name: ''),
User.create(name: 'Юзер Кастомерович', email: 'user2@test.com', password: '123456', password_confirmation: '123456', confirmed_at: Time.now.utc, info: '', skills: [], role: 'customer', phone_number: '', company_name: ''),
User.create(name: 'Юзер Анибодиевич', email: 'user3@test.com', password: '123456', password_confirmation: '123456', confirmed_at: Time.now.utc, info: '', skills: [], role: '', phone_number: '', company_name: '')]

[Project.create(title: '(Демо) Доработать приложение на Swift', user_id: User.first.id, info: "Добрый вечер исполнители. Есть готовый проект на Swift калькулятор. Нужна помощь в доработке функционала 3-х кнопок. Есть общий лейбел ввода данных где отображаются цифры есть дублирующий где отображаются вся информация 45+5-6=44 - это как пример. Удалить посимвольно. Заблокировать ввод пока не удалено до знака равно(45+5-6=44). Все остальные данные пересчитывать при нажатии знака равно. 2. удалить последнее действие 45+5-6=44, при первой нажатии удаляем =44, при втором -6 и т.д 3. Вернуть последнее действие вернуть - 6 при втором нажатии возвращаем = 44", skills: 'Swift,iOS', project_type: 'project_type', cost: 25, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: '(Демо) Разработка Приложения под IOS', user_id: User.second.id, info: "Всем привет! Ищем Middle IOS Developer, для добавления новых фич + рефакторинг в уже существующем приложении написанном на Swift. В общей сложности работ месяца на 4. Разработчик должен будет работать фул-тайм.", skills: 'Swift,iOS', project_type: 'project_type', cost: 2000, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: '(Демо) Разработчик на SWIFT', user_id: User.third.id, info: "На постоянную удаленную работу требуется разработчик Mac OS (Objective-C / Swift).В ключевые обязанности будет входить: Разработка native GUI приложения под Mac OS X согласно подробному ТЗ и дизайну (тематика: оптимизация OS). Проведение технических исследований и экспертиз. Работа с системой контроля версий и баг трекерами. Мы ищем специалиста, который: Обладает 3-х летним опытом коммерческой разработки под MacOS X или iOS (Objective-C; Swift отдаем преимущество). Понимает принципы работы GUI приложений. Знает принципы проектирования ПО и оптимизации производительности. Обладает опытом разработки многопоточных приложений. Знает английский язык на уровне technical read/writeУсловия, которые мы предлагаем:- Возможность работать удаленно из любой точки мира- Достойная зарплата (в USD) плюс бонусы по результатам работы- Оплачиваемый отпуск- Полная занятость, гибкий график- Работа в дружном коллективе- Перспективы профессионального роста*Мы будем признательны, если Вы укажете размер желаемой заработной платы в своем резюме или сопроводительном письме, однако окончательный уровень финансового вознаграждения будет обсуждаться с каждым соискателем индивидуально.На предложение, со стороны компании, напрямую влияют: соответствие вышеперечисленным требованиям, объем и тематика портфолио (мы готовы рассмотреть работы выполненные также и для iOS), Ваши знания, продемонстрированные на техническом интервью. Отправляя резюме ОБЯЗАТЕЛЬНО в сопроводительном письме укажите свое ФИО, контактный e–mail и ССЫЛКУ НА ПОРТФОЛИО (или список проектов).", skills: 'Swift,iOS', project_type: 'project_type', cost: 2500, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: '(Демо) Junior Ruby on Rails developer', user_id: User.first.id, info: "В команду нужен начинающий RoR программист для помощи по проекту. Работа удаленная, связь через чат в мессенджерах или скайп голосом  Работа хорошо подойдет начинающим.Требования: Опыт в web, SaaS, Rails. Опыт с Linux серверами, Docker (не обязательно),Хороший уровень front-end, Опыт удаленной работы. Спасибо.", skills: 'RoR,Linux', project_type: 'project_type', cost: 600, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: '(Демо) Настроить добавление в БД (Ruby on Rails)', user_id: User.second.id, info: "Есть restclient ruby и встроенная библиотека json - выгружается ответ API, но есть какая-то проблема с его разбором или проблема с этим вот restclient, потому что уходит в таймаут. Возможно ActiveRecord не настроен правильно, так как не добавляет в БД. Нужно просто в этом ориентироваться, чтобы решить проблему.Если вы шарите в Ruby - пишите!", skills: 'RoR,Ruby', project_type: 'project_type', cost: 1, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: '(Демо) Web игра', user_id: User.third.id, info: "Необходимо разработать веб игру по типу игры 'змейка', где игра будет проходить в реальном времени, где множество игроков играют в роли змейки или червя на одной карте и пытаются нарастить свою массу, длину и размер, чтобы стать самой большой змейкой и попасть в список лидеров.", skills: 'Node.js', project_type: 'project_type', cost: 300, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: '(Демо) Разработка JavaScript игр', user_id: User.first.id, info: "Нужен разработчик простых JavaScript игр на платформе Spark AR для постоянного сотрудничества. Spark AR: https://sparkar.facebook.com/ar-studio/ Желательно город Киев.", skills: 'React,HTML,CSS', project_type: 'project_type', cost: 800, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: "(Демо) Требуется C# Asp.Net/MVC .NetCore разработчик на длительный срок.", user_id: User.second.id, info: "Требуется Asp.Net C# программист для удалённой работы. Необходимые навыки: Знания ООП, шаблонов проектирования.- Уверенное знание Asp.Net/MVC/C#, Asp.Net Core- Разработка на Backend с применением TDD- Возможность работать как над веб так и над C# проектами (разработка библиотек)- Опыт разработки БД, MsSql, администрирования - jQuery, Angular, Backbone, TypeScript и т.д.- ajax, javasrcipt, html, css - Системы контроля версий, Git.- Опыт вёртски- Работа с багтрекером.- Ответственность, коммуникабельность, возможность быть онлайн в рабочее время- Знание английского на уровне понимания задач, участия в чтении переписки.Работа в Agile команде на полный день. Просьба, если Вы рассчитываете на подработку - не откликаться на данную вакансию - вакнсия на ПОЛНЫЙ ДЕНЬ!", skills: 'MsSql,.NET,C#,VBS', project_type: 'project_type', cost: 1700, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: '(Демо) Создание Игрового сервера: C#, JS,HTML,CSS,MySQL', user_id: User.third.id, info: "Требуется Программист для создания игрового сервера на платформе Rage MP для GTA 5 владеющий: C#, JS, MySQL, HTML, CSS. Требуется программист как на отдельном ЯП, так и на всех требующихся.Программист требуется как на постоянную основу так и на аутсорсинг.Сервер состоит из 20-30 модулей, разной сложности. Приблизительное протяженность работ 2-4 месяца с момента начала разработок.  Заработная плата за каждый модуль. Стоимость услуг обговаривается индивидуально с каждым разработчиком, заранее после ознакомления с ТЗ, оплата сразу после тестирования. За 1 модуль цена от 500 р до 10.000 рублей. На фиксированную ЗП не рассматриваем.  Оплата любым удобным для вас способ, либо через данный сайт либо напрямую.Требуется:1 постоянный программист. (Оплата за каждый модуль + надбавка за внедрения других модулей)2 программиста на аутсорс. (Оплата за каждый модуль)Вся необходимая документация по Rage Multiplayer находится в открытом доступе, а так же поддержка на форуме. При оставление заявки, указывайте:Ваши контакты для связи (Skype, discord, VK, WhatsApp, Telegram)Ваш опыт в разработкахВаши предпочтения(одному все делать или же нужны помощники)", skills: 'C#,JS,MySQL,HTML,CSS', project_type: 'project_type', cost: 1000, cost_type: 'price', deadline: rand(1.month).seconds.from_now),
 Project.create(title: '(Демо) Требуется PHP (Laravel) разработчик для постоянной работы.', user_id: User.first.id, info: "Доброе время суток! Требуется full stack (PHP, Laravel) программист для постоянной работы. Требования: Уверенное знание PHP (2+ года)- Опыт использования фреймворка Laravel (1+ год)- Знание и использование принципов ООП- Опыт проектирования и работы с MySQL + понимание, как писать оптимизированные запросы к БД- Знания JavaScript; AJAX- Опыт написания и работы с REST API- Понимание основ HTML, CSS, BootstrapЛичные качества:- Умение ориентироваться и разбираться в чужом коде- Умение давать адекватную оценку на разработку и выполнять поставленные задачи в оговоренный срок- Организованность, ответственность, профессионализм, добросовестностьУсловия:- Удаленная работа и свободный график- Оплата: 10$/час, выплата 1 раз в месяц- Минимум 5 продуктивных часов в день, 5 дней в неделю- Учёт продуктивных часов при помощи Time Tracking программы (yaware)", skills: 'PHP,HTML,CSS,Bootstrap', project_type: 'project_type', cost: 1000, cost_type: 'price', deadline: rand(1.month).seconds.from_now)]
